import { useState } from "react";
import { useAuth } from "../../contexts/AuthContext";
import { ToastContainer, toast } from "react-toastify";
import React from "react";
import Head from "next/head";
import Layout from "../../components/Layout";
import PageHeading from "../../components/PageHeading";
import Div from "../../components/Div";
import Spacing from "../../components/Spacing";

export default function ForgotPassword() {
  const [email, setEmail] = useState("");
  const { forgotPassword } = useAuth();

  const handleSubmit = async (e) => {
    e.preventDefault();
    try {
      await forgotPassword(email);
      toast.success(
        "If an account with that email exists, we have sent you an email to reset your password."
      );
    } catch (error) {
      toast.error("Failed to send reset password email");
    }
  };

  return (
    <>
      <Head>
        <title>Forgot Password - Portfolify </title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout>
        <PageHeading bgSrc="/images/search_banner.png" />
        <Spacing lg="30" md="20" />
        <Div className="auth-container cs-radius_7">
          <h2>Forgot Password</h2>
          <form onSubmit={handleSubmit}>
            <Div className="cs-auth_input_container">
              <label>Email</label>
              <input
                type="email"
                value={email}
                onChange={(e) => setEmail(e.target.value)}
                placeholder="Email"
                required
                className="cs-auth_input"
              />
            </Div>
            <Div className="cs-auth_button_container">
              <button type="submit" className="cs-btn cs-style1 cs-auth_button">
                Reset password
              </button>
            </Div>
          </form>
        </Div>
        <ToastContainer />
      </Layout>
    </>
  );
}
