import { useState } from "react";
import { useRouter } from "next/router";
import { useAuth } from "../../contexts/AuthContext";
import { ToastContainer, toast } from "react-toastify";
import React from "react";
import Head from "next/head";
import Layout from "../../components/Layout";
import PageHeading from "../../components/PageHeading";
import Div from "../../components/Div";
import Spacing from "../../components/Spacing";

export default function ResetPassword() {
  const [password, setPassword] = useState("");
  const { resetPassword } = useAuth();
  const router = useRouter();
  const { token } = router.query; // Assuming the URL includes a ?token=<TOKEN> parameter

  const handleSubmit = async (e) => {
    e.preventDefault();
    if (!token || typeof token !== "string") {
      toast.error("Token is invalid or expired");
      return;
    }
    try {
      await resetPassword(password, token);
      toast.success("Your password has been reset successfully");
      router.push("/auth/login");
    } catch (error) {
      toast.error("Failed to reset password");
    }
  };

  return (
    <>
      <Head>
        <title>Reset Password - Portfolify </title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout>
        <PageHeading bgSrc="/images/search_banner.png" />
        <Spacing lg="30" md="20" />
        <Div className="auth-container cs-radius_7">
          <h2>Reset Password</h2>
          <form onSubmit={handleSubmit}>
            <Div className="cs-auth_input_container">
              <label>Password</label>
              <input
                type="password"
                value={password}
                onChange={(e) => setPassword(e.target.value)}
                placeholder="New password"
                required
                className="cs-auth_input"
              />
            </Div>
            <Div className="cs-auth_button_container">
              <button type="submit" className="cs-btn cs-style1 cs-auth_button">
                Change password
              </button>
            </Div>
          </form>
        </Div>
        <ToastContainer />
      </Layout>
    </>
  );
}
