import React from 'react';
import Head from 'next/head';
import Layout from '../components/Layout';
import Hero from '../components/Hero';
import UserHeading from "../components/PageHeading/UserHeading"
import Div from "../components/Div"

const UserPage = () => {
  const userData = {
    username: "somePerson",
    userDescription: "Some personal statement",
    userBanner: "/images/about_hero_bg.jpeg",
    userProfilePicture: "/images/portfolio_6.jpeg"
  }
  const userExperience = {
    title: "Job Position",
    company: "Company Name",
    startDate: "About a year ago",
    endDate: "Still ongoing",
    description: "I do things"
  }
  const userEductation = {
    institution: "Some university",
    degree: "Bachelors",
    fieldOfStudy: "Random Field",
    startDate: "About 3 years ago",
    endDate: "Last year",
  }
  const userReference = {
    name: "Mr. Person",
    contactInfo: "Should probably be private",
    relationship: "Not my dad",
  }
  return (
    <>
      <Head>
        <title>Portfolio - Portfolify </title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout>
        {/* <Hero
          title="Creativity In <br/>Our Blood Line"
          subtitle="We deliver best problem solving solution for our client and provide finest finishing product in present and upcoming future."
          btnText="Get a Quote"
          btnLink="/contact"
          scrollDownId="#service"
          bgImageUrl="/images/hero_bg.jpg"
        /> */}
        <UserHeading 
          title="My portfolio" 
          bgSrc={userData.userBanner} 
          pageLinkText="Portfolio" 
          userImage={userData.userProfilePicture}
          />
        <Div>
          <h2>{userData.username}</h2>
          <p>{userData.userDescription}</p>
        </Div>
        <Div
        style={{ backgroundImage: `url(${userData.userProfilePicture})`, width: "424px", height: "465px"}}
        >

        </Div>
      </Layout>
    </>
  )
}

export default UserPage
